### ISSUE TITLE
have error on 15.4.1 IOS

### ISSUE THREAD

**Issue by choowx2002** [kaichii/pdf_viewer#17]
loadDocument(io.File file) async {
    var documentFile = await PDFDocument.fromFile(file);
    print("documentcwx"+documentFile.toString());
    setState(
      () {
        document = documentFile;
      },
    );
  }
  
   body: Center(
        child: document == null
            ? Center(
                child: CircularProgressIndicator(),
              )
            : PDFViewer(
                document: document!,
                showIndicator: false,
                showPicker: false,
              ),
      ),
      
(first time create issue  any rules i need to know?)
     im using 1.0.4 
     When i run in android and ios simulator 16.2 all is fine 
     but it crash and come below error when run on IOS 15.4.1
     
     ----------------FIREBASE CRASHLYTICS----------------
2023-08-16 17:29:46.154278+0800 Runner[52085:1657670] flutter: RangeError (index): Invalid value: Valid value range is empty: 0
2023-08-16 17:29:46.155712+0800 Runner[52085:1657670] flutter: 
#0      _Array.[] (dart:core-patch/array.dart:10:36)
#1      _PDFViewerState._loadPage (package:easy_pdf_viewer/src/viewer.dart:159:16)
#2      _PDFViewerState.didChangeDependencies (package:easy_pdf_viewer/src/viewer.dart:121:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5036:11)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#11     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#19     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#25     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#26     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#30     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#44     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#55     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#67     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#71     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#75     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#79     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#84     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#88     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#91     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#93     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#98     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#99     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#100    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#101    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#102    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#103    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#104    _rootRun (dart:async/zone.dart:1391:13)
#105    _CustomZone.run (dart:async/zone.dart:1293:19)
#106    _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
#107    _invoke (dart:ui/hooks.dart:150:10)
#108    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#109    _drawFrame (dart:ui/hooks.dart:115:31)
2023-08-16 17:29:46.157763+0800 Runner[52085:1657670] flutter: ---------------------

**Comment by choowx2002** [comment]
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (9 weeks ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
